# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GaussianBandit": "01_thompson_sampler.ipynb",
         "ActivationDoesNotExist": "02_neural_networks.ipynb",
         "InputDimensionNotCorrect": "02_neural_networks.ipynb",
         "LossFunctionNotDefined": "02_neural_networks.ipynb",
         "DenseLayer": "02_neural_networks.ipynb",
         "NeuralNetwork": "02_neural_networks.ipynb",
         "DropoutLayer": "02_neural_networks.ipynb",
         "AttentionDropoutLayer": "02_neural_networks.ipynb"}

modules = ["thompson_sampler.py",
           "neural_networks.py"]

doc_url = "https://wooohoooo.github.io/neuralThompsonTrainer/"

git_url = "https://github.com/wooohoooo/neuralThompsonTrainer/tree/master/"

def custom_doc_links(name): return None
